import type { SceneGraph, SceneNode } from '@open-pencil/scene-graph'
import { deriveSlashVariantProperties } from '@open-pencil/scene-graph/variant-properties'

import { sceneNodeToDesignDocument } from './from-scene-graph'
import type { ExportHTMLFile } from './html-export'
import { serializeHTML } from './serialize'

export type StorybookFramework = 'react' | 'vue' | 'html'

export interface ExportStorybookOptions {
  framework?: StorybookFramework
  /** Limit the export to one page. Defaults to every page. */
  pageId?: string
  /** Identifies the document in each story's first line; see `generatedStorySource`. */
  source?: string
  /** Repository-relative `.fig`/`.pen` path; adds an `openpencil://` design link to stories. */
  linkPath?: string
  /** Renders a variant to PNG; each story then shows it next to the link as its design. */
  renderDesignImage?: (nodeId: string) => Promise<Uint8Array>
}

interface StoryVariant {
  values: string[]
  node: SceneNode
}

interface StoryGroup {
  page: string
  title: string
  name: string
  props: { name: string; options: string[] }[]
  variants: StoryVariant[]
  linkNode?: string
}

const FRAMEWORKS: Record<StorybookFramework, { types: string; imports: string; render: string }> = {
  react: {
    types: '@storybook/react-vite',
    imports: "import { createElement } from 'react'\n",
    render: "createElement('div', { dangerouslySetInnerHTML: { __html: variantHTML(args) } })"
  },
  vue: {
    types: '@storybook/vue3-vite',
    imports: "import { h } from 'vue'\n",
    render: "({ setup: () => () => h('div', { innerHTML: variantHTML(args) }) })"
  },
  html: { types: '@storybook/html-vite', imports: '', render: 'variantHTML(args)' }
}

/** A JSON string that stays on one line inside a `//` comment. */
function commentLiteral(value: string): string {
  return JSON.stringify(value).replaceAll('\u2028', '\\u2028').replaceAll('\u2029', '\\u2029')
}

/**
 * The first line of every story, naming the document and page it was generated from, so
 * a re-export can find the files it owns and leave every other story alone.
 */
function generatedStoryHeader(source: string, page: string): string {
  return `// Generated by OpenPencil from ${commentLiteral(source)}, page ${commentLiteral(page)}. Re-export to update; edits are overwritten.`
}

const QUOTED = String.raw`"(?:[^"\\]|\\.)*"`
const GENERATED_HEADER = new RegExp(
  String.raw`^// Generated by OpenPencil from (${QUOTED}), page (${QUOTED})\. Re-export to update; edits are overwritten\.$`
)
function parseQuoted(quoted: string | undefined): string | null {
  if (quoted === undefined) return null
  try {
    const value: unknown = JSON.parse(quoted)
    return typeof value === 'string' ? value : null
  } catch {
    return null
  }
}

/** The document and page a story file was generated from, or null for any other file. */
export function generatedStorySource(content: string): { source: string; page: string } | null {
  // A checkout with `core.autocrlf` turns the generated LF endings into CRLF.
  const match = GENERATED_HEADER.exec(content.split(/\r?\n/, 1)[0] ?? '')
  const source = parseQuoted(match?.[1])
  const page = parseQuoted(match?.[2])
  return source !== null && page !== null ? { source, page } : null
}

const lit = (value: string) => JSON.stringify(value)

function isExported(node: SceneNode): boolean {
  return node.visible && !node.internalOnly
}

function nodeHTML(graph: SceneGraph, node: SceneNode): string {
  return serializeHTML(sceneNodeToDesignDocument(graph, node.id, false))
}

function unique(values: string[]): string[] {
  return [...new Set(values)]
}

/** Variants whose property values collide are told apart by layer name instead. */
function distinctVariants(group: StoryGroup, names: string[]): StoryGroup {
  const keys = group.variants.map((variant) => JSON.stringify(variant.values))
  if (new Set(keys).size === keys.length) return group
  const used = new Set<string>()
  const labels = names.map((name) => {
    let label = name
    for (let i = 2; used.has(label); i++) label = `${name} ${i}`
    used.add(label)
    return label
  })
  return {
    ...group,
    props: [{ name: 'Variant', options: labels }],
    variants: group.variants.map((variant, i) => ({ ...variant, values: [labels[i] ?? ''] }))
  }
}

function componentSetGroup(graph: SceneGraph, page: SceneNode, set: SceneNode): StoryGroup {
  const definitions = set.componentPropertyDefinitions.filter((def) => def.type === 'VARIANT')
  const components = graph
    .getChildren(set.id)
    .filter((child) => child.type === 'COMPONENT' && isExported(child))
  const variants = components.map((component) => ({
    values: definitions.map((def) => component.componentPropertyValues[def.name] ?? ''),
    node: component
  }))
  const props = definitions.map((def, index) => ({
    name: def.name,
    options: unique([...(def.variantOptions ?? []), ...variants.map((v) => v.values[index] ?? '')])
  }))
  return distinctVariants(
    {
      page: page.name,
      title: `${page.name}/${set.name}`,
      name: set.name,
      props,
      variants,
      linkNode: set.name
    },
    components.map((component) => component.name)
  )
}

function componentGroup(graph: SceneGraph, page: SceneNode, component: SceneNode): StoryGroup {
  return {
    page: page.name,
    title: `${page.name}/${component.name}`,
    name: component.name,
    props: [],
    variants: [{ values: [], node: component }],
    linkNode: component.name
  }
}

/** `Button/Primary`, `Button/Secondary` → one `Button` group with a derived variant property. */
function slashGroups(
  graph: SceneGraph,
  page: SceneNode,
  prefix: string,
  components: SceneNode[]
): StoryGroup[] {
  const derived = deriveSlashVariantProperties(components, () => '')
  if (!derived) return components.map((component) => componentGroup(graph, page, component))
  const props = derived.definitions.map((def) => ({
    name: def.name,
    options: def.variantOptions ?? []
  }))
  const variants = components.map((component) => {
    const values = derived.variants.get(component.id)?.componentPropertyValues ?? {}
    return {
      values: props.map((prop) => values[prop.name] ?? ''),
      node: component
    }
  })
  return [
    distinctVariants(
      { page: page.name, title: `${page.name}/${prefix}`, name: prefix, props, variants },
      components.map((component) => component.name)
    )
  ]
}

function collectGroups(graph: SceneGraph, page: SceneNode): StoryGroup[] {
  const groups: StoryGroup[] = []
  const slashed = new Map<string, SceneNode[]>()
  const visit = (node: SceneNode) => {
    if (!isExported(node) || node.type === 'INSTANCE') return
    if (node.type === 'COMPONENT_SET') {
      const group = componentSetGroup(graph, page, node)
      if (group.variants.length > 0) groups.push(group)
      return
    }
    if (node.type === 'COMPONENT') {
      const prefix = node.name.split('/')[0]?.trim()
      if (!node.name.includes('/') || !prefix) groups.push(componentGroup(graph, page, node))
      else slashed.set(prefix, [...(slashed.get(prefix) ?? []), node])
      return
    }
    for (const child of graph.getChildren(node.id)) visit(child)
  }
  for (const child of graph.getChildren(page.id)) visit(child)
  for (const [prefix, components] of slashed)
    groups.push(...slashGroups(graph, page, prefix, components))
  return groups
}

function identifier(text: string, used: Set<string>): string {
  const words = text.split(/[^A-Za-z0-9]+/).filter(Boolean)
  const base = words.map((word) => word.charAt(0).toUpperCase() + word.slice(1)).join('')
  const name = /^[A-Za-z]/.test(base) ? base : `Variant${base}`
  let candidate = name
  for (let i = 2; used.has(candidate.toLowerCase()); i++) candidate = `${name}${i}`
  used.add(candidate.toLowerCase())
  return candidate
}

interface ModuleContext {
  graph: SceneGraph
  framework: StorybookFramework
  source?: string
  linkPath?: string
  /** Layers whose name no other layer carries; only those can be linked to by name. */
  uniqueNames: Set<string>
  /** Import path of each variant's design image, by variant index. */
  images?: string[]
}

function designParameter(entries: string[]): string {
  return entries.length === 0 ? '' : `parameters: { design: [${entries.join(', ')}] }, `
}

function designLink(context: ModuleContext, node: string | undefined): string[] {
  if (!context.linkPath || !node) return []
  const url = `openpencil://open?file=${encodeURIComponent(context.linkPath)}&node=${encodeURIComponent(node)}`
  return [`{ name: 'OpenPencil', type: 'link', url: ${lit(url)} }`]
}

/** Story export names, which also name the design images. */
function storyNames(group: StoryGroup): string[] {
  const used = new Set<string>()
  return group.variants.map((variant) =>
    identifier(group.props.length === 0 ? 'Default' : variant.values.join(' '), used)
  )
}

function storyModule(group: StoryGroup, context: ModuleContext): string {
  const { framework, uniqueNames, images } = context
  const { types, imports, render } = FRAMEWORKS[framework]
  const { props, variants } = group
  const argsType =
    props.length === 0
      ? 'Record<string, never>'
      : `{ ${props.map((p) => `${lit(p.name)}: ${p.options.map(lit).join(' | ')}`).join('; ')} }`
  const argsLiteral = (values: string[]) =>
    `{ ${props.map((p, i) => `${lit(p.name)}: ${lit(values[i] ?? '')}`).join(', ')} }`
  const argTypes = props
    .map(
      (p) => `${lit(p.name)}: { control: 'select', options: [${p.options.map(lit).join(', ')}] }`
    )
    .join(', ')
  const names = storyNames(group)
  const stories = variants.map((variant, i) => {
    const label =
      props.length === 0
        ? 'Default'
        : props.map((p, j) => `${p.name}=${variant.values[j] ?? ''}`).join(', ')
    // The link scheme addresses layers by name, so only a name no other layer carries is linked.
    const linkNode = [variant.node.name, group.linkNode].find(
      (name) => name !== undefined && uniqueNames.has(name)
    )
    const design = [
      ...designLink(context, linkNode),
      ...(images?.[i] ? [`{ name: 'Design', type: 'image', url: design${i} }`] : [])
    ]
    return `export const ${names[i]}: Story = { name: ${lit(label)}, ${designParameter(design)}args: ${argsLiteral(variant.values)} }`
  })
  // `new URL(…, import.meta.url)` is bundled like an import but needs no ambient PNG types.
  const imageImports = (images ?? []).map(
    (path, i) => `const design${i} = new URL(${lit(`./${path}`)}, import.meta.url).href\n`
  )

  return `${generatedStoryHeader(context.source ?? 'a design document', group.page)}
import type { Meta, StoryObj } from '${types}'
${imports}${imageImports.join('')}
type Args = ${argsType}

const variants: Record<string, string> = {
${variants.map((v) => `  ${lit(JSON.stringify(v.values))}: ${lit(nodeHTML(context.graph, v.node))},`).join('\n')}
}

function variantHTML(args: Args): string {
  const key = JSON.stringify([${props.map((p) => `args[${lit(p.name)}]`).join(', ')}])
  const html = variants[key]
  if (html === undefined) throw new Error(${lit(`${group.name} has no variant `)} + key)
  return html
}

const meta = {
  title: ${lit(group.title)},
  ${designParameter(designLink(context, group.linkNode && uniqueNames.has(group.linkNode) ? group.linkNode : undefined))}args: ${argsLiteral(variants[0]?.values ?? [])},
  argTypes: { ${argTypes} },
  render: (args) => ${render}
} satisfies Meta<Args>

export default meta
type Story = StoryObj<Args>

${stories.join('\n')}
`
}

/** Storybook ids ignore case and punctuation, so `Library/Card` and `library/card` collide. */
function storyId(title: string): string {
  return title
    .toLowerCase()
    .replaceAll(/[^\p{L}\p{N}]+/gu, '-')
    .replaceAll(/^-|-$/g, '')
}

function uniqueLayerNames(graph: SceneGraph): Set<string> {
  const counts = new Map<string, number>()
  for (const node of graph.getAllNodes()) counts.set(node.name, (counts.get(node.name) ?? 0) + 1)
  return new Set([...counts].filter(([, count]) => count === 1).map(([name]) => name))
}

/**
 * Generate one CSF3 `.stories.ts` file per component or component set, plus a
 * `<Name>.design/` folder of variant images when `renderDesignImage` is given.
 */
export async function exportStorybook(
  graph: SceneGraph,
  options: ExportStorybookOptions = {}
): Promise<ExportHTMLFile[]> {
  const uniqueNames = uniqueLayerNames(graph)
  const usedFiles = new Set<string>()
  const usedTitles = new Set<string>()
  const files: ExportHTMLFile[] = []
  // Every page is named, so a `pageId` export picks the same file names as a full one.
  for (const page of graph.getPages()) {
    for (const group of collectGroups(graph, page)) {
      // Same-named components on a page would share a title, and Storybook story ids.
      let title = group.title
      for (let i = 2; usedTitles.has(storyId(title)); i++) title = `${group.title} ${i}`
      usedTitles.add(storyId(title))
      group.title = title
      const base = identifier(group.name, usedFiles)
      if (options.pageId && page.id !== options.pageId) continue
      const render = options.renderDesignImage
      const images = render && storyNames(group).map((name) => `${base}.design/${name}.png`)
      if (render && images) {
        for (const [i, variant] of group.variants.entries())
          files.push({ path: images[i] ?? '', content: await render(variant.node.id) })
      }
      const framework = options.framework ?? 'react'
      const context = { ...options, graph, framework, uniqueNames, images }
      files.push({ path: `${base}.stories.ts`, content: storyModule(group, context) })
    }
  }
  return files
}
