import { watch } from 'node:fs'
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises'
import { basename, dirname, extname, isAbsolute, join, relative, resolve } from 'node:path'

import { BUILTIN_IO_FORMATS, IORegistry } from '@open-pencil/core/io'
import {
  exportStorybook,
  generatedStorySource,
  type StorybookFramework
} from '@open-pencil/dom-css'

import { requireFile } from '#cli/app-client'
import { applyExportFontPolicy } from '#cli/export-font-policy'
import { ok, printError } from '#cli/format'
import { loadDocument, populateWholeDocument, requirePage } from '#cli/headless'

interface StorybookArgs {
  file?: string
  output?: string
  page?: string
  node?: string
  framework: string
  'design-images': boolean
  'font-policy': string
  watch?: boolean
}

const io = new IORegistry(BUILTIN_IO_FORMATS)
const FRAMEWORKS = new Set<string>(['react', 'vue', 'html'] satisfies StorybookFramework[])

function isStorybookFramework(value: string): value is StorybookFramework {
  return FRAMEWORKS.has(value)
}

/** Repository-relative path for `openpencil://` links, when the file sits under the cwd. */
function linkPath(file: string): string | undefined {
  const path = relative(process.cwd(), resolve(file)).split('\\').join('/')
  return path.startsWith('../') || isAbsolute(path) ? undefined : path
}

/**
 * Removes the stories a previous export of `source` generated, so a component deleted or
 * renamed in the document does not linger. Any other story — hand-written, or generated
 * from another document — is kept, and refuses the export if it would be overwritten.
 */
async function replaceGeneratedStories(
  outputDir: string,
  source: string,
  paths: Set<string>,
  onePage: boolean
): Promise<void> {
  const owned: string[] = []
  for (const entry of await readdir(outputDir)) {
    if (!entry.endsWith('.stories.ts')) continue
    const path = join(outputDir, entry)
    const owner = generatedStorySource(await readFile(path, 'utf8'))
    // A one-page export replaces its own files and keeps the other pages' stories.
    if (owner === source) {
      if (!onePage || paths.has(entry)) owned.push(entry)
    } else if (paths.has(entry))
      throw new Error(
        `${path} was ${owner ? `generated from ${owner}` : 'not generated by OpenPencil'}; export ${source} to another --output directory.`
      )
  }
  for (const entry of owned) {
    await rm(join(outputDir, entry))
    await rm(join(outputDir, entry.replace(/\.stories\.ts$/, '.design')), {
      recursive: true,
      force: true
    })
  }
}

async function writeStories(
  args: StorybookArgs,
  file: string,
  framework: StorybookFramework,
  outputDir: string
): Promise<number> {
  const graph = await loadDocument(file)
  const pageId = args.page ? requirePage(graph, args.page).id : undefined
  populateWholeDocument(graph)
  if (args['design-images']) {
    const pageIds = pageId ? [pageId] : graph.getPages().map((page) => page.id)
    await applyExportFontPolicy(graph, pageIds, 'PNG', args['font-policy'])
  }
  const link = linkPath(file)
  const source = link ?? basename(file)
  const files = await exportStorybook(graph, {
    framework,
    pageId,
    source,
    linkPath: link,
    renderDesignImage: args['design-images']
      ? async (nodeId) => {
          const result = await io.exportContent(
            'png',
            { graph, target: { scope: 'node', nodeId } },
            { format: 'PNG', scale: 2 }
          )
          if (!(result.data instanceof Uint8Array)) throw new Error('PNG export returned text.')
          return result.data
        }
      : undefined
  })
  if (files.length === 0)
    throw new Error(`No components found in ${args.page ? `page "${args.page}"` : 'the document'}.`)

  await mkdir(outputDir, { recursive: true })
  const paths = new Set(files.map((story) => story.path))
  await replaceGeneratedStories(outputDir, source, paths, pageId !== undefined)
  for (const story of files) {
    const path = join(outputDir, story.path)
    await mkdir(dirname(path), { recursive: true })
    await writeFile(path, story.content)
  }
  return files.filter((story) => story.path.endsWith('.stories.ts')).length
}

/** Re-exports on every save; editors that save by rename are why the folder is watched. */
function watchDocument(file: string, onChange: () => Promise<void>): void {
  let timer: ReturnType<typeof setTimeout> | undefined
  let running = Promise.resolve()
  watch(dirname(resolve(file)), (_event, name) => {
    if (name !== basename(file)) return
    clearTimeout(timer)
    timer = setTimeout(() => {
      running = running.then(onChange)
    }, 200)
  })
}

export async function exportStorybookFromFile(args: StorybookArgs): Promise<void> {
  if (args.node) {
    printError('--node is not supported for Storybook export. Use --page to limit it to one page.')
    process.exit(1)
  }
  const framework = args.framework
  if (!isStorybookFramework(framework)) {
    printError(`Invalid Storybook framework "${framework}". Use react, vue, or html.`)
    process.exit(1)
  }
  const file = requireFile(args.file)
  const outputDir = resolve(args.output ?? `${basename(file, extname(file))}-stories`)
  const run = async () => {
    const count = await writeStories(args, file, framework, outputDir)
    console.log(ok(`Exported ${count} story files to ${outputDir}`))
  }

  try {
    await run()
  } catch (error) {
    printError(error instanceof Error ? error.message : String(error))
    process.exit(1)
  }
  if (!args.watch) return

  // A save can land mid-write or break the document; report it and keep watching.
  watchDocument(file, () =>
    run().catch((error: unknown) =>
      printError(error instanceof Error ? error.message : String(error))
    )
  )
  console.log(ok(`Watching ${file} for changes`))
}
